### ISSUE TITLE
wish: please define "pseudo-fork" in the README

### ISSUE THREAD

**Issue by markstos** [michaelsbradleyjr/traits.js#1]
Pseudo-fork is not a a standard term. 

Could you clarify what you mean by then, or avoid using the term?

It seems that either it's a fork or it isn't.

**Comment by michaelsbradleyjr** [comment]
You're right, I was being a bit too creative with my terminology back in 2013. This repo is, in essence, a fork. That being said, I have been meaning to put an "Inactive" notice at the top of the README, with a note explaining that my original plans for development got superseded by my taking up ClojureScript.

I left the repo in place as I noted that the package on the npm registry was being downloaded regularly (it still is, I think), and packages without a corresponding repo have always struck me as "more orphaned" than those tied to a git repo, evan an inactive one.

I'll make a note to take care of the README adjustments later today or tomorrow. Thank you for your input.

**Comment by markstos** [comment]
Sounds good. If you are updating the README, you might point to this repo, which is now a more-active fork of your repo:

https://github.com/YR/trait

I was in touch with the author there today and he plans to clean it up a bit more and it on npm, but it's not there now. If you don't plan to develop it further, he might be interested to take over the "light-trait" namespace from you. His version could simply be a "new major version" in the semantic-versioning sense, so people would expect there might be breaking changes.

**Comment by michaelsbradleyjr** [comment]
Will do.

**Comment by michaelsbradleyjr** [comment]
Forgot to address the latter part of your message. Actually, I don't control the _[light-traits](https://www.npmjs.com/package/light-traits)_ namespace; mine is _traits.js_:

https://www.npmjs.com/package/traits.js

**Comment by michaelsbradleyjr** [comment]
Okay, I've revised the README. I also published a point release via npm (`v0.4.1`) so that the README on npmjs.com is also up-to-date.

**Comment by markstos** [comment]
Thanks!
